version: "3"
services:
  # Postgres
  postgres:
    image: postgres:latest
    ports:
      # Attach to local port :54321
      - "35432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: saas
    # Make sure log colors show up correctly
    tty: true
