input CreateClassLevelInput {
  name: String!
  classId: String!
  characterId: String!
}

type ClassLevel {
  id: String!
  class: Class!
  character: Character!
  # TODO: Create Datetime type
  # createdAt:
  # updatedAt:
}

type Query {
  getClassLevel(id: String!): ClassLevel  @authentication
}

type Mutation {
  createClassLevel(input: CreateClassLevelInput!): ClassLevel  @authentication
  deleteClassLevel(id: String!): Boolean  @authentication
}
