input CreateCharacterInput {
  name: String!
  projectId: String!
}

type Character {
  id: String!
  name: String!
  archetypeLevels: [ArchetypeLevel]!
  project: Project!
  user: User!
  rolls: [Roll]!
  # TODO: Create Datetime type
  # createdAt:
  # updatedAt:
}

type Query {
  getCharacter(id: String!): Character  @authentication
  getCharacters: [Character]!  @authentication
}

type Mutation {
  createCharacter(input: CreateCharacterInput): Character! @authentication
  deleteCharacter(id: String!): Boolean!  @authentication
}
