input CreateProject {
  name: String!
  # TODO: Update this to indicate people being invited
  userIds: [String!]
}

type Project {
  id: String!
  name: String!
  owner: User!
  users: [User!]
  characters: [Character!]
}

type Query {
  getProject(id: String!): Project
}

type Mutation {
  createProject(input: CreateProject!): Project! @authentication
  deleteProject(id: String!): Boolean! @authentication
}
