input CreateProject {
  name: String!
  userIds: [String!]
}

type Project {
  id: String!
  name: String!
  owner: User!
  users: [User!]
}

type Query {
  getProject(id: String!): Project
}

type Mutation {
  createProject(project: CreateProject!): Project!
  deleteProject(id: String!): Boolean!
}
