input CreateClassInput {
  name: String!
  subclasses: [String!]!
}

type Class {
  id: String!
  name: String!
  subclasses: [String!]!
  # TODO: Create Datetime type
  # createdAt:
  # updatedAt:
}

type Query {
  getClass(id: String!): Class  @authentication
  getClasses: [Class!]!  @authentication
}

type Mutation {
  createClass(input: CreateClassInput!): Class  @authentication
  deleteClass(id: String!): Boolean  @authentication
}
